### ISSUE TITLE
Centralized resource tagging

### ISSUE THREAD

**Issue by rafavallina** [aws/aws-proton-public-roadmap#2]
Enable three types of tags in AWS proton that are applied to all resources in each environment or service:
1. Automated Proton tags: includes tags to identify all resources provisioned through Proton, all resources in a particular environment and all resources in a particular service
2. Administrator defined tags: allows administrators to define a series of tags in each template that will be automatically applied to all resources that use it (for example, administrators can define a `user:type:Fargate` task to all templates based on Fargate)
3. End-user defined tags: allows end users creating environment or services to define tags at the time of creation that will be applied to all resources in that service or environment

**Comment by zbintliff** [comment]
Hey Rafa! Can we also include tags on the actual proton resources too? That is, tags on the Environments, Templates, and Service Templates?  I'm not 100% up to day with the terminology. 

As you know we deploy to many accounts and we prefer to use the same spec to deploy everywhere. Rather than enforcing environment/template naming standards we would love to use a tag based approach. Tag lookup and selection on those resources would be very valuable and remove the dependency on names.

**Comment by rafavallina** [comment]
Hi Zach! Excellent question. The answer is definitely yes - I will update the text above to reflect it, but Proton resources themselves would also be tagged. All tags that would be used for the underlying resources would also be used for the Proton resources as well.

**Comment by rafavallina** [comment]
This is now live https://aws.amazon.com/about-aws/whats-new/2021/03/aws-proton-now-supports-tagging-capabilities/
