### ISSUE TITLE
Bug: Unable to delete/update failed Pipelines 

### ISSUE THREAD

**Issue by mubbashir10** [aws/aws-proton-public-roadmap#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please fix the issue where failed pipelines:
- can't be updated/deleted
- are stuck on "In Progress"
- doesn't show any notifications when they fail

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I was writing a tutorial on AWS Proton and created a couple of services (for testing) that didn't deploy successfully and the pipelines failed for them. Now I can't update the services/service instances, nor I can delete them. It's just stuck on "In progress". I thought it would eventually be changed once the pipelines time out but that didn't happen either. 

**Are you currently working around this issue?**
Umm, I tried going to ECS and deleting the resources manually but this is not optimal

**Additional context**
I put my GitHub repo id without a username (i.e `aws-proton-nodejs-sample`) due to which the pipeline failed. After waiting for around an hour (without getting any notifications etc.) I went to the AWS CodePipeline and noticed that the pipeline had failed because I needed to put the repo id with a username (i.e `mubbashir10/aws-proton-nodejs-sample`)

**Attachments**
The failed pipelines have "In progress" status
![image](https://user-images.githubusercontent.com/13771105/101268110-79e08c00-3781-11eb-9f67-a5775f851bc3.png)

If I try to delete any of the failed services, it fails
![image](https://user-images.githubusercontent.com/13771105/101268173-0723e080-3782-11eb-8f15-47e270952748.png)

If I try to update the source, I can't see source/Github fields anymore
![image](https://user-images.githubusercontent.com/13771105/101268406-376c7e80-3784-11eb-84d5-ad77d10b0813.png)

**Comment by mrletourneau** [comment]
Hello and thanks for reaching out. Sorry you've ran into this issue! I will take a look and get these deployments cleaned up for you.

**Comment by mrletourneau** [comment]
Thanks again for reaching out and bringing our attention to this issue. We have fixed your deployments, so you should be able to delete these stuck deployments now. We have also cut a ticket internally to look into the unexpected AWS CodePipeline behavior.

Cheers!

**Comment by rafavallina** [comment]
Thanks team! I'm going to go ahead and close this issue, as it has been solved.

As a closing comment, I want to make sure I recommend reaching out to AWS support for bugs (https://console.aws.amazon.com/support/home) in addition to opening an issue here, if that's ok! The reason is that we can't really make any commitments to fixing any particular issue with an account through this forum.

It is still very useful for us to hear about these issues, so please keep the input coming!

**Comment by mubbashir10** [comment]
@rafavallina sorry I thought it would make more sense to post Proton specific issues (cause there was already one) here. Will be mindful of that in the future. 

Thanks for the help guys, much appreciated!

**Comment by rafavallina** [comment]
@mubbashir10 Thanks! No reason to be sorry at all, you did the right thing. My comment is more because I want to make sure I don't create the impression that the team will be available on Github to solve issues - we would eventually not be able to respond and that would be frustrating for customers. But I really appreciate you opening the issue!
